import type { PresentationMessage, PresentationParam } from './types';

const messages: Record<string, string> = {
  raw: '{text}',

  'studio.plan_set': '[studio] plan 设定:{count} 棒',
  'studio.dispatch_started': '[studio] dispatch[#{taskIndex}] → pet:{petId}',
  'studio.task_status_changed': '[studio] task[#{taskIndex}] → {status}',
  'studio.wiki_updated': '[studio] wiki 更新 {count} 项',
  'studio.dispatch_finished': '[studio] dispatch {dispatchId} → {status}',
  'studio.event': '[studio] event: {type}',

  'tool.read_file.label': '读文件',
  'tool.read_file.detail': '读取文件内容',
  'tool.view_file_chunk.label': '看片段',
  'tool.view_file_chunk.detail': '查看文件片段',
  'tool.stat_path.label': '看属性',
  'tool.stat_path.detail': '查看路径信息',
  'tool.write_file.label': '写文件',
  'tool.write_file.detail': '写入文件内容',
  'tool.write_file.detail.append.path': '追加 {path}',
  'tool.write_file.detail.write.path': '写入 {path}',
  'tool.update_file.label': '改文件',
  'tool.update_file.detail': '更新文件内容',
  'tool.update_file.detail.replace.path': '替换 {path}',
  'tool.update_file.detail.replace_all.path': '批量替换 {path}',
  'tool.multi_edit.label': '批量修改',
  'tool.multi_edit.detail': '执行多组替换',
  'tool.apply_file_patch.label': '应用补丁',
  'tool.apply_file_patch.detail': '按补丁更新文件',
  'tool.apply_unified_patch.label': '应用 diff',
  'tool.apply_unified_patch.detail': '当前目录 · -p{strip}{dryRun}',
  'tool.validate_structured_file.label': '验证结构',
  'tool.validate_structured_file.detail': '验证结构化文件',
  'tool.move_path.label': '移动文件',
  'tool.move_path.detail': '移动文件或目录',
  'tool.copy_path.label': '复制文件',
  'tool.copy_path.detail': '复制文件或目录',
  'tool.mkdir_path.label': '建目录',
  'tool.mkdir_path.detail': '创建目录',
  'tool.list_dir.label': '列目录',
  'tool.list_dir.detail': '查看目录内容',
  'tool.glob_search.label': '找文件',
  'tool.glob_search.detail': '按模式搜索文件',
  'tool.grep_search.label': '搜内容',
  'tool.grep_search.detail': '递归搜索文件内容',
  'tool.run_shell.label': '执行命令',
  'tool.run_shell.detail': '执行 shell 命令',
  'tool.download_file.label': '下载文件',
  'tool.download_file.detail': '下载远程文件',
  'tool.unknown.detail': '',

  'tool.result.failed': '失败 · {error}',
  'tool.result.completed': '已完成',
  'tool.capability_search.result.found': '找到 capability：{candidates}',
  'tool.capability_search.result.found.query': '找到 capability：{candidates} · query: {query}',
  'tool.capability_search.result.empty': '未找到 capability 候选',
  'tool.capability_search.result.empty.query': '未找到 capability 候选 · query: {query}',
  'tool.capability_search.result.done': '已搜索 capability',
  'tool.write_file.result.ok': '已写入',
  'tool.write_file.result.ok.path': '已写入 {path}',
  'tool.view_file_chunk.result.ok': '已读取片段',
  'tool.stat_path.result.ok': '已查看',
  'tool.stat_path.result.ok.path': '已查看 {path}',
  'tool.update_file.result.ok': '已更新',
  'tool.update_file.result.ok.path': '已更新 {path}',
  'tool.multi_edit.result.ok': '已批量修改',
  'tool.multi_edit.result.ok.path': '已批量修改 {path}',
  'tool.apply_file_patch.result.ok': '已应用补丁',
  'tool.apply_file_patch.result.ok.path': '已应用补丁 {path}',
  'tool.apply_unified_patch.result.applied': '已应用 diff',
  'tool.apply_unified_patch.result.applied.path': '已应用 {cwd}',
  'tool.apply_unified_patch.result.dry_run': '预检通过',
  'tool.apply_unified_patch.result.dry_run.path': '预检通过 {cwd}',
  'tool.validate_structured_file.result.ok': '已验证结构',
  'tool.validate_structured_file.result.ok.path': '已验证 {path}',
  'tool.move_path.result.ok': '已移动',
  'tool.move_path.result.ok.path': '已移动到 {destination}',
  'tool.copy_path.result.ok': '已复制',
  'tool.copy_path.result.ok.path': '已复制到 {destination}',
  'tool.mkdir_path.result.ok': '已创建',
  'tool.mkdir_path.result.ok.path': '已创建 {path}',
  'tool.glob_search.result.ok': '已完成搜索',
  'tool.glob_search.result.ok.output': '找到 {output}',
  'tool.grep_search.result.ok': '已完成搜索',
  'tool.grep_search.result.ok.output': '命中 {output}',
  'tool.download_file.result.ok': '已下载',
  'tool.download_file.result.ok.path': '已下载到 {path}',
  'tool.list_dir.result.ok': '已列目录',
  'tool.list_dir.result.ok.output': '已列出 {output}',
  'tool.read_file.result.ok': '已读取',
  'tool.read_file.result.ok.output': '已读取 {output}',
  'tool.run_shell.result.ok': '已执行',
  'tool.run_shell.result.ok.output': '结果 {output}',
};

function formatParam(value: PresentationParam) {
  if (value === undefined || value === null) return '';
  return String(value);
}

export function renderZhCN(message: PresentationMessage | null): string {
  if (!message) return '';
  const template = messages[message.key] ?? message.key;
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, key: string) =>
    formatParam(message.params?.[key]),
  );
}
