export const TUI_TEXT = {
  defaultPetName: '宠物',
  defaultPetSummary: 'pet 未加载',
  unknownSpecies: '未知物种',
  unknownStage: '未知阶段',
  growthValue: (value: number) => `成长值 ${value}`,
  emptyHistory: (petName: string) => `和 ${petName} 聊天吧。`,
  helpIdle: '/new 新会话 · /help 帮助 · /quit 退出',
  helpBusy: 'Ctrl+C 打断 · 再按一次退出',
  inputBusy: '> 处理中…',
  inputPlaceholder: '输入消息',
  approvalFreeReplyPlaceholder: '输入自由回复，或按 ↑ 返回选择器',
  approvalHelp: '↑↓ 选择 · Enter 确认 · Esc 自由输入',
  approvalHeading: (petId?: string) => (petId ? `[${petId} 想问你]` : '需要确认'),
  approvalFallbackPrompt: '当前流程需要你的确认，请直接回复继续或说明下一步。',
  approvalWaiting: (petId?: string) => (petId ? `等待你的决定(${petId})` : '等待你的决定'),
  approvalClosed: '已关闭确认面板 · 可自由输入',
  approvalApprove: '批准',
  approvalReject: '拒绝',
  approvalApproveExecution: '批准执行',
  approvalContinue: '继续',
  approvalStopHere: '停在这里',
  approvalAllowSession: (command: string) => `本次会话授权：${command}`,
  studioExited: '已退出 Studio 模式',
  studioExitedToChat: '已退出 Studio 模式，回到单 pet chat',
  studioNotActive: '当前不在 Studio 模式',
  studioModeEntered: (conversationId: string) =>
    `已进入 Studio 模式 (conversation=${conversationId.slice(0, 8)})。后续输入都属于此会话，输入 /chat 或 /studio 退出。`,
  disconnectedCannotSend: '未连接，无法发送',
  busyCannotSend: '当前任务仍在进行中，按 Ctrl+C 或 Esc 打断',
  unknownCommand: (raw: string) => `未知命令：${raw}`,
  exportNoSession: '当前没有可导出的会话。',
  exportSucceeded: (filePath: string) => `已导出 transcript：${filePath}`,
  exportFailed: (message: string) => `导出 transcript 失败：${message}`,
  secondCtrlCExit: '收到第二次 Ctrl+C，立即退出 TUI。',
  interruptRequested: '已发送打断请求。再次按 Ctrl+C 可直接退出 TUI。',
  exiting: '正在退出 TUI。',
  busyPhaseInterrupting: '正在打断',
  busyPhaseReplying: '正在回复',
  busyPhaseThinking: '正在思考',
  busyPhaseUsingTools: '正在调用能力或工具',
  busyPhaseLongRunning: '仍在处理中',
  modelOutputChars: (count: number) => `${count} 字`,
  statusInitializing: '初始化中',
  statusReady: '就绪',
  statusErrorRecovered: '出错，已恢复输入',
  interrupted: '[interrupted]',
  errorLine: (message: string) => `出错: ${message}`,
  studioEmptyTurn: (outcome: 'done' | 'stopped') => `[studio] turn ${outcome} (无最终输出)`,
  studioStoppedReason: (reason: string) => `[studio] stopped: ${reason}`,
  studioErrorLine: (message: string) => `[studio 出错] ${message}`,
} as const;
