export const TUI_TEXT = {
  defaultPetName: '宠物',
  defaultPetSummary: 'pet 未加载',
  unknownSpecies: '未知物种',
  unknownStage: '未知阶段',
  growthValue: (value: number) => `成长值 ${value}`,
  emptyHistory: (petName: string) => `和 ${petName} 聊天吧。`,
  helpIdle: '/new 新会话 · /resume 恢复 · /help 帮助 · /quit 退出',
  helpBusy: 'Ctrl+C 打断 · 再按一次退出',
  commandPaletteTitle: '命令',
  commandPaletteEmpty: '没有匹配命令',
  fileMentionTitle: '文件',
  fileMentionEmpty: '没有匹配路径',
  inputBusy: '> 处理中…',
  inputPlaceholder: '输入消息',
  approvalFreeReplyPlaceholder: '输入回复，或按 ↑↓ 选择',
  approvalHelp: '空输入 ↑↓ 选择 · 输入回复后 ↑↓ 移动光标 · Enter 确认 · Esc 取消',
  approvalRespondRequiresInput: '请先输入回复内容。',
  approvalHeading: (petId?: string) => (petId ? `[${petId} 想问你]` : '需要确认'),
  approvalFallbackPrompt: '当前流程需要你的确认，请使用当前确认面板应答。',
  approvalWaiting: (petId?: string) => (petId ? `等待你的决定(${petId})` : '等待你的决定'),
  approvalClosed: '确认面板已关闭或过期，请等待刷新',
  approvalApprove: '批准',
  approvalReject: '拒绝',
  approvalApproveExecution: '批准执行',
  approvalContinue: '继续',
  approvalStopHere: '停在这里',
  studioExited: '已退出 Studio 模式',
  studioExitedToChat: '已退出 Studio 模式，回到单 pet chat',
  studioNotActive: '当前不在 Studio 模式',
  studioModeEntered: (conversationId: string) =>
    `已进入 Studio 模式 (conversation=${conversationId.slice(0, 8)})。后续输入都属于此会话，输入 /chat 或 /studio 退出。`,
  disconnectedCannotSend: '未连接，无法发送',
  busyCannotSend: '当前任务仍在进行中，按 Ctrl+C 或 Esc 打断',
  waitingForReply: '等待回复',
  studioUserMessage: (userRequest: string) => `[studio] ${userRequest}`,
  studioRunning: 'Studio 编排中',
  reviewDisconnectedCannotSubmit: '未连接，无法提交确认。',
  reviewSubmitting: '提交确认',
  interrupting: '正在打断',
  interruptRequestedStatus: '已请求打断',
  interruptRequestedLocalRelease: '打断请求已发送，本地先释放输入；迟到的旧响应会被忽略。',
  interruptedStatus: '已打断',
  newSessionCreated: '已创建新会话',
  connectionConnecting: '连接本地服务',
  connectionDisconnected: '未连接',
  connectionClosed: '连接断开',
  connectionReconnectFailed: '连接断开，重连失败',
  connectionRetrying: (seconds: number, attempt: number, maxAttempts: number) =>
    `本地服务暂不可用，${seconds}s 后重试 ${attempt}/${maxAttempts}`,
  connectionReconnectRetrying: (seconds: number, attempt: number, maxAttempts: number) =>
    `连接断开，${seconds}s 后重连 ${attempt}/${maxAttempts}`,
  connectionUnavailable: (port: number) =>
    `无法连接本地服务（port ${port}），请先运行 pinpawo-agent run`,
  initializationFailed: (message: string) => `初始化失败：${message}`,
  websocketError: (message: string) => `WebSocket 出错：${message}`,
  reconnectFailed: (message: string) => `重连失败：${message}`,
  actorContextUnavailable: '无法加载宠物信息，使用默认名称',
  unknownCommand: (raw: string) => `未知命令：${raw}`,
  exportNoSession: '当前没有可导出的会话。',
  exportSucceeded: (filePath: string) => `已导出 transcript：${filePath}`,
  exportFailed: (message: string) => `导出 transcript 失败：${message}`,
  externalEditorUnavailable: '未配置 $VISUAL 或 $EDITOR，无法打开外部编辑器。',
  externalEditorOpening: '正在打开外部编辑器…保存并退出后会回填输入框。',
  externalEditorLoaded: '已从外部编辑器载入草稿。',
  externalEditorEmpty: '外部编辑器未留下内容。',
  externalEditorFailed: (message: string) => `外部编辑器失败：${message}`,
  resumeLoading: '正在加载可恢复会话…',
  resumeEmpty: '暂无可恢复会话。',
  resumeFailed: (message: string) => `加载可恢复会话失败：${message}`,
  resumeSucceeded: (title: string) => `已恢复会话：${title}`,
  resumePickerTitle: '可恢复会话',
  resumePickerHelp: '↑↓ 选择 · Enter 恢复 · Esc 取消',
  resumeActiveBadge: '当前',
  secondCtrlCExit: '收到第二次 Ctrl+C，立即退出 TUI。',
  interruptRequested: '已发送打断请求。再次按 Ctrl+C 可直接退出 TUI。',
  exiting: '正在退出 TUI。',
  busyPhaseInterrupting: '正在打断',
  busyPhaseReplying: '正在回复',
  busyPhaseThinking: '正在思考',
  busyPhaseUsingTools: '正在调用能力或工具',
  busyPhaseLongRunning: '仍在处理中',
  modelOutputChars: (count: number) => `${count} 字`,
  statusInitializing: '初始化中',
  statusReady: '就绪',
  statusErrorRecovered: '出错，已恢复输入',
  runtimeInfoLine: (model: string, cwd: string, studioConfigPath: string, studioConfigSource: string, contextWindow: string) =>
    `模型: ${model} · 工作目录: ${cwd} · Studio 配置: ${studioConfigPath} (${studioConfigSource}) · 上下文窗口上限: ${contextWindow}`,
  tokenUsageLine: (inputTokens: string, outputTokens: string, totalTokens: string, contextWindow: string | null, ratio: string | null) => (
    ratio
      ? `Token 用量：入/出/总 = ${inputTokens} / ${outputTokens} / ${totalTokens} (${ratio}，上下文上限 ${contextWindow})`
      : `Token 用量：入/出/总 = ${inputTokens} / ${outputTokens} / ${totalTokens}`
  ),
  interrupted: '[interrupted]',
  errorLine: (message: string) => `出错：${message}`,
  studioEmptyTurn: (outcome: 'done' | 'stopped') => `[studio] turn ${outcome} (无最终输出)`,
  studioStoppedReason: (reason: string) => `[studio] stopped: ${reason}`,
  studioErrorLine: (message: string) => `[studio 出错] ${message}`,
  studioErrorRecovered: 'Studio 出错，已恢复输入',
  operationStarted: '开始',
  operationRunning: '进行中',
  operationFailed: '失败',
  operationInterrupted: '中断',
  operationCompleted: '完成',
  studioProgressPlanSet: (taskCount: number) => `[studio] plan 设定：${taskCount} 项`,
  studioProgressDispatchStarted: (taskIndex: string | number, petId: string) =>
    `[studio] dispatch[#${taskIndex}] → pet:${petId}`,
  studioProgressTaskStatusChanged: (taskIndex: string | number, status: string) =>
    `[studio] task[#${taskIndex}] → ${status}`,
  studioProgressWikiUpdated: (changedCount: number) => `[studio] wiki 更新 ${changedCount} 项`,
  studioProgressDispatchFinished: (dispatchId: string, status: string) =>
    `[studio] dispatch ${dispatchId} → ${status}`,
  studioProgressUnknown: (type: string) => `[studio] event: ${type}`,
} as const;
