import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve } from 'node:path';

export type InitCommandOptions = {
  dir?: string;
  force?: boolean;
  exampleCapability?: boolean;
};

type WrittenFile = {
  path: string;
  status: 'created' | 'skipped';
};

function expandHome(path: string): string {
  if (path === '~') return homedir();
  if (path.startsWith('~/')) return resolve(homedir(), path.slice(2));
  return path;
}

function writeNewFile(path: string, content: string, force: boolean, written: WrittenFile[]): void {
  if (existsSync(path) && !force) {
    written.push({ path, status: 'skipped' });
    return;
  }
  writeFileSync(path, content, 'utf-8');
  written.push({ path, status: 'created' });
}

function envTemplate(): string {
  return `# PinPawo Local Agent quick-start configuration.
# You can also run "pinpawo-agent login" to save these values to config.json.

# Server
API_BASE_URL=https://your-api.example.com
HASURA_ENDPOINT=https://your-hasura.example.com/v1/graphql
AGENT_TOKEN=your-agent-token-here
HASURA_JWT=eyJ...

# LLM (OpenAI-compatible)
LLM_API_KEY=sk-xxx
LLM_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
LLM_MODEL=qwen3.5-plus
# Optional. Fill this for custom models when automatic inference is not enough.
LLM_CONTEXT_WINDOW_TOKENS=

# Local runtime
PINPAWO_WORKDIR=${homedir()}
PINPAWO_BROWSER_BACKEND=auto
LOCAL_SERVER_PORT=3210

# MediaCrawler (optional)
MEDIACRAWLER_DIR=
XHS_COOKIE=
`;
}

function exampleManifest(): string {
  return JSON.stringify({
    id: 'hello-pinpawo',
    name: 'Hello PinPawo',
    description: 'Minimal example capability generated by pinpawo-agent init.',
    icon: 'Sparkles',
    color: '#2563eb',
    defaultEnabled: true,
    builtIn: false,
  }, null, 2) + '\n';
}

function exampleCapabilityIndex(): string {
  return `export function createCapability() {
  return {
    name: 'hello-pinpawo',
    description: 'Minimal example capability generated by pinpawo-agent init.',
    createRuntime() {
      return {
        instructions: [
          'You can use this example capability as a starting point for local PinPawo agent extensions.',
        ],
      };
    },
  };
}
`;
}

export function scaffoldQuickInstall(options: InitCommandOptions = {}): {
  rootDir: string;
  capabilitiesDir: string;
  written: WrittenFile[];
} {
  const rootDir = resolve(expandHome(options.dir ?? '~/.pinpawo'));
  const capabilitiesDir = resolve(rootDir, 'capabilities');
  const force = options.force ?? false;
  const includeExampleCapability = options.exampleCapability ?? true;
  const written: WrittenFile[] = [];

  mkdirSync(capabilitiesDir, { recursive: true });
  writeNewFile(resolve(rootDir, '.env'), envTemplate(), force, written);

  if (includeExampleCapability) {
    const exampleDir = resolve(capabilitiesDir, 'hello-pinpawo');
    mkdirSync(exampleDir, { recursive: true });
    writeNewFile(resolve(exampleDir, 'manifest.json'), exampleManifest(), force, written);
    writeNewFile(resolve(exampleDir, 'index.js'), exampleCapabilityIndex(), force, written);
  }

  return { rootDir, capabilitiesDir, written };
}

export async function runInit(options: InitCommandOptions = {}): Promise<void> {
  const result = scaffoldQuickInstall(options);
  const created = result.written.filter((file) => file.status === 'created').map((file) => file.path);
  const skipped = result.written.filter((file) => file.status === 'skipped').map((file) => file.path);
  const exampleCapabilityDir = resolve(result.capabilitiesDir, 'hello-pinpawo');

  process.stdout.write(`PinPawo local agent scaffold ready at ${result.rootDir}\n`);
  if (created.length > 0) {
    process.stdout.write(`Created:\n${created.map((path) => `  - ${path}`).join('\n')}\n`);
  }
  if (skipped.length > 0) {
    process.stdout.write(`Skipped existing files:\n${skipped.map((path) => `  - ${path}`).join('\n')}\n`);
    process.stdout.write('Use --force to overwrite generated scaffold files.\n');
  }
  process.stdout.write('\nNext steps:\n');
  process.stdout.write('  1. Edit the generated .env or run: pinpawo-agent login\n');
  process.stdout.write(`  2. Validate the example capability: pinpawo-agent capability validate ${exampleCapabilityDir}\n`);
  process.stdout.write('  3. Start the TUI: pinpawo-agent tui\n');
}
