import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve } from 'node:path';

export type InitCommandOptions = {
  dir?: string;
  force?: boolean;
  exampleCapability?: boolean;
};

type WrittenFile = {
  path: string;
  status: 'created' | 'skipped';
};

function expandHome(path: string): string {
  if (path === '~') return homedir();
  if (path.startsWith('~/')) return resolve(homedir(), path.slice(2));
  return path;
}

function writeNewFile(path: string, content: string, force: boolean, written: WrittenFile[]): void {
  if (existsSync(path) && !force) {
    written.push({ path, status: 'skipped' });
    return;
  }
  writeFileSync(path, content, 'utf-8');
  written.push({ path, status: 'created' });
}

function envTemplate(): string {
  return `# PinPawo Local Agent quick-start configuration.
# Model profiles, including credentials and endpoints, belong in config.json
# under "models". They are not read from environment variables.

# Optional structured-output auto repair. Disabled by default.
LLM_STRUCTURED_OUTPUT_AUTO_REPAIR=
# Defaults to 1 when auto repair is enabled; capped at 3.
LLM_STRUCTURED_OUTPUT_REPAIR_MAX_RETRIES=

# Local runtime
PINPAWO_WORKDIR=${homedir()}
PINPAWO_BROWSER_BACKEND=auto
LOCAL_SERVER_PORT=3210
`;
}

function exampleCapabilityDocument(): string {
  return `---
name: hello-pinpawo
description: Minimal example capability generated by pinpawo init.
uses:
  - bash
version: 1
icon: Sparkles
color: "#2563eb"
defaultEnabled: true
---

# Hello PinPawo

Use this example capability as a starting point for local PinPawo agent extensions.

## Workflow

Inspect the relevant files with the tools supplied by the \`bash\` Toolkit, perform the requested work, validate the result, and summarize the changed files and verification.
`;
}

export function scaffoldQuickInstall(options: InitCommandOptions = {}): {
  rootDir: string;
  capabilitiesDir: string;
  written: WrittenFile[];
} {
  const rootDir = resolve(expandHome(options.dir ?? '~/.pinpawo'));
  const capabilitiesDir = resolve(rootDir, 'capabilities');
  const force = options.force ?? false;
  const includeExampleCapability = options.exampleCapability ?? true;
  const written: WrittenFile[] = [];

  mkdirSync(capabilitiesDir, { recursive: true });
  writeNewFile(resolve(rootDir, '.env'), envTemplate(), force, written);

  if (includeExampleCapability) {
    const exampleDir = resolve(capabilitiesDir, 'hello-pinpawo');
    mkdirSync(exampleDir, { recursive: true });
    writeNewFile(
      resolve(exampleDir, 'CAPABILITY.md'),
      exampleCapabilityDocument(),
      force,
      written,
    );
  }

  return { rootDir, capabilitiesDir, written };
}

export async function runInit(options: InitCommandOptions = {}): Promise<void> {
  const result = scaffoldQuickInstall(options);
  const created = result.written.filter((file) => file.status === 'created').map((file) => file.path);
  const skipped = result.written.filter((file) => file.status === 'skipped').map((file) => file.path);
  const exampleCapabilityDir = resolve(result.capabilitiesDir, 'hello-pinpawo');

  process.stdout.write(`PinPawo local agent scaffold ready at ${result.rootDir}\n`);
  if (created.length > 0) {
    process.stdout.write(`Created:\n${created.map((path) => `  - ${path}`).join('\n')}\n`);
  }
  if (skipped.length > 0) {
    process.stdout.write(`Skipped existing files:\n${skipped.map((path) => `  - ${path}`).join('\n')}\n`);
    process.stdout.write('Use --force to overwrite generated scaffold files.\n');
  }
  process.stdout.write('\nNext steps:\n');
  process.stdout.write('  1. Define a model profile under "models" in ~/.pinpawo/config.json\n');
  process.stdout.write(`  2. Validate the example capability: pinpawo capability validate ${exampleCapabilityDir}\n`);
  process.stdout.write('  3. Start the TUI: pinpawo tui\n');
}
