import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { resolve } from 'node:path';
import {
  createModelProfile,
  MODEL_PROFILES_VERSION,
  type ModelProfileV1,
} from '../modelProfiles';
import {
  findLlmModelPresetByKey,
  inferLlmModelPreset,
} from '../llmModelPresets';

export type InitCommandOptions = {
  dir?: string;
  force?: boolean;
  exampleCapability?: boolean;
};

type WrittenFile = {
  path: string;
  status: 'created' | 'skipped';
};

function expandHome(path: string): string {
  if (path === '~') return homedir();
  if (path.startsWith('~/')) return resolve(homedir(), path.slice(2));
  return path;
}

function writeNewFile(path: string, content: string, force: boolean, written: WrittenFile[]): void {
  if (existsSync(path) && !force) {
    written.push({ path, status: 'skipped' });
    return;
  }
  writeFileSync(path, content, 'utf-8');
  written.push({ path, status: 'created' });
}

function envTemplate(): string {
  return `# PinPawo Local Agent quick-start configuration.
# Model profiles, including credentials and endpoints, belong in config.json
# under "models". They are not read from environment variables.

# Optional structured-output auto repair. Disabled by default.
LLM_STRUCTURED_OUTPUT_AUTO_REPAIR=
# Defaults to 1 when auto repair is enabled; capped at 3.
LLM_STRUCTURED_OUTPUT_REPAIR_MAX_RETRIES=

# Local runtime
PINPAWO_WORKDIR=${homedir()}
PINPAWO_BROWSER_BACKEND=auto
LOCAL_SERVER_PORT=3210
`;
}

function parseDotEnv(content: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const separator = trimmed.indexOf('=');
    if (separator < 1) continue;
    const key = trimmed.slice(0, separator).trim();
    values[key] = trimmed.slice(separator + 1).trim().replace(/^[\"']|[\"']$/g, '');
  }
  return values;
}

function toPositiveInteger(value: string | undefined): number | undefined {
  if (!value?.trim()) return undefined;
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined;
}

function serializeModelConfig(profile: ModelProfileV1): string {
  return `${JSON.stringify({
    models: {
      version: MODEL_PROFILES_VERSION,
      defaultProfileId: profile.id,
      profiles: {
        [profile.id]: profile,
      },
    },
  }, null, 2)}\n`;
}

function modelConfigTemplate(env: Record<string, string>): string {
  const apiKey = env.LLM_API_KEY?.trim();
  const baseUrl = env.LLM_BASE_URL?.trim();
  const model = env.LLM_MODEL?.trim();
  if (apiKey && baseUrl && model) {
    try {
      const requestedPreset = findLlmModelPresetByKey(env.LLM_MODEL_PRESET);
      const inferredPreset = inferLlmModelPreset(model);
      const preset = requestedPreset?.key === inferredPreset?.key
        ? requestedPreset
        : inferredPreset;
      return serializeModelConfig(createModelProfile({
        id: 'primary',
        label: preset?.label ?? model,
        ...(preset ? { sourcePreset: preset.key } : {}),
        apiKey,
        baseUrl,
        model,
        contextWindowTokens: toPositiveInteger(env.LLM_CONTEXT_WINDOW_TOKENS),
      }));
    } catch {
      // Leave invalid legacy values untouched in .env and provide an editable profile instead.
    }
  }

  return serializeModelConfig(createModelProfile({
    id: 'primary',
    label: 'Qwen 3.7 Max',
    sourcePreset: 'qwen',
    apiKey: 'replace-with-your-api-key',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen3.7-max',
  }));
}

function exampleCapabilityDocument(): string {
  return `---
name: hello-pinpawo
description: Minimal example capability generated by pinpawo init.
uses:
  - bash
version: 1
icon: Sparkles
color: "#2563eb"
defaultEnabled: true
---

# Hello PinPawo

Use this example capability as a starting point for local PinPawo agent extensions.

## Workflow

Inspect the relevant files with the tools supplied by the \`bash\` Toolkit, perform the requested work, validate the result, and summarize the changed files and verification.
`;
}

export function scaffoldQuickInstall(options: InitCommandOptions = {}): {
  rootDir: string;
  capabilitiesDir: string;
  written: WrittenFile[];
} {
  const rootDir = resolve(expandHome(options.dir ?? '~/.pinpawo'));
  const capabilitiesDir = resolve(rootDir, 'capabilities');
  const force = options.force ?? false;
  const includeExampleCapability = options.exampleCapability ?? true;
  const written: WrittenFile[] = [];
  const envPath = resolve(rootDir, '.env');
  const configPath = resolve(rootDir, 'config.json');
  const existingEnv = existsSync(envPath) ? parseDotEnv(readFileSync(envPath, 'utf-8')) : {};
  const needsConfig = force || !existsSync(configPath);

  mkdirSync(capabilitiesDir, { recursive: true });
  writeNewFile(envPath, envTemplate(), force, written);
  writeNewFile(configPath, needsConfig ? modelConfigTemplate(existingEnv) : '', force, written);

  if (includeExampleCapability) {
    const exampleDir = resolve(capabilitiesDir, 'hello-pinpawo');
    mkdirSync(exampleDir, { recursive: true });
    writeNewFile(
      resolve(exampleDir, 'CAPABILITY.md'),
      exampleCapabilityDocument(),
      force,
      written,
    );
  }

  return { rootDir, capabilitiesDir, written };
}

export async function runInit(options: InitCommandOptions = {}): Promise<void> {
  const result = scaffoldQuickInstall(options);
  const created = result.written.filter((file) => file.status === 'created').map((file) => file.path);
  const skipped = result.written.filter((file) => file.status === 'skipped').map((file) => file.path);
  const exampleCapabilityDir = resolve(result.capabilitiesDir, 'hello-pinpawo');

  process.stdout.write(`PinPawo local agent scaffold ready at ${result.rootDir}\n`);
  if (created.length > 0) {
    process.stdout.write(`Created:\n${created.map((path) => `  - ${path}`).join('\n')}\n`);
  }
  if (skipped.length > 0) {
    process.stdout.write(`Skipped existing files:\n${skipped.map((path) => `  - ${path}`).join('\n')}\n`);
    process.stdout.write('Use --force to overwrite generated scaffold files.\n');
  }
  process.stdout.write('\nNext steps:\n');
  process.stdout.write(`  1. Edit ${resolve(result.rootDir, 'config.json')} and replace the model profile credentials\n`);
  process.stdout.write(`  2. Validate the example capability: pinpawo capability validate ${exampleCapabilityDir}\n`);
  process.stdout.write('  3. Start the TUI: pinpawo tui\n');
}
