#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
env_file="${1:-"$script_dir/.env"}"

if [[ -f "$env_file" && "${LANGFUSE_ENV_OVERWRITE:-}" != "1" ]]; then
  echo "Langfuse env already exists: $env_file"
  exit 0
fi

if [[ -f "$env_file" ]]; then
  echo "Overwriting Langfuse env: $env_file"
fi

rand_hex() {
  openssl rand -hex "$1"
}

rand_base64() {
  openssl rand -base64 "$1"
}

nextauth_secret="$(rand_base64 32)"
salt="$(rand_base64 32)"
encryption_key="$(rand_hex 32)"
postgres_password="$(rand_hex 16)"
clickhouse_password="$(rand_hex 16)"
redis_auth="$(rand_hex 16)"
minio_password="$(rand_hex 16)"
init_user_password="$(rand_hex 16)"
langfuse_public_key="lf_pk_$(rand_hex 12)"
langfuse_secret_key="lf_sk_$(rand_hex 16)"

cat > "$env_file" <<EOF
# Generated by infra/langfuse/bootstrap-env.sh.
# Local test secrets only. Do not commit this file.

NEXTAUTH_URL=http://localhost:3000
LANGFUSE_WEB_PORT=3000
LANGFUSE_WORKER_PORT=3030
LANGFUSE_MINIO_PORT=9090
LANGFUSE_MINIO_CONSOLE_PORT=9091
LANGFUSE_POSTGRES_PORT=5432
LANGFUSE_CLICKHOUSE_HTTP_PORT=8123
LANGFUSE_CLICKHOUSE_NATIVE_PORT=9000
LANGFUSE_REDIS_PORT=6379

NEXTAUTH_SECRET=$nextauth_secret
SALT=$salt
ENCRYPTION_KEY=$encryption_key
TELEMETRY_ENABLED=false
LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false

POSTGRES_USER=postgres
POSTGRES_PASSWORD=$postgres_password
POSTGRES_DB=postgres
DATABASE_URL=postgresql://postgres:$postgres_password@postgres:5432/postgres

CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=$clickhouse_password
CLICKHOUSE_CLUSTER_ENABLED=false

REDIS_AUTH=$redis_auth

MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=$minio_password
LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_EVENT_UPLOAD_REGION=auto
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=$minio_password
LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://minio:9000
LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/
LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_MEDIA_UPLOAD_REGION=auto
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=$minio_password
LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://localhost:9090
LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/
LANGFUSE_S3_BATCH_EXPORT_ENABLED=false
LANGFUSE_S3_BATCH_EXPORT_BUCKET=langfuse
LANGFUSE_S3_BATCH_EXPORT_PREFIX=exports/
LANGFUSE_S3_BATCH_EXPORT_REGION=auto
LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=http://minio:9000
LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=http://localhost:9090
LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=minio
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=$minio_password
LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=true

LANGFUSE_INIT_ORG_ID=pinpawo-local
LANGFUSE_INIT_ORG_NAME=PinPawo Local
LANGFUSE_INIT_PROJECT_ID=pinpawo-agent-local
LANGFUSE_INIT_PROJECT_NAME=PinPawo Agent Local
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=$langfuse_public_key
LANGFUSE_INIT_PROJECT_SECRET_KEY=$langfuse_secret_key
LANGFUSE_INIT_USER_EMAIL=pinpawo-local@example.com
LANGFUSE_INIT_USER_NAME=PinPawo Local
LANGFUSE_INIT_USER_PASSWORD=$init_user_password

LANGFUSE_BASE_URL=http://localhost:3000
LANGFUSE_PUBLIC_KEY=$langfuse_public_key
LANGFUSE_SECRET_KEY=$langfuse_secret_key
EOF

chmod 600 "$env_file"
echo "Created Langfuse env: $env_file"
